;; Test with tree cars, three places, three boxes
(define (problem transport)
    (:domain transport)
    (:objects car1 car2 car3 place1 place2 place3 box1 box2 box3)
    (:init
        (car car1)
        (car car2)
        (car car3)
        (place place1)
        (place place2)
        (place place3)
        (box box1)
        (box box2)
        (box box3)
        (full car1)
        (empty car2)
        (empty car3)
        (at box1 place1)
        (at box2 place3)
        (at box3 car1)
        (at car1 place1)
        (at car2 place3)
        (at car3 place1)
    )
    (:goal (and
        (at box1 place2)
        (at box2 car1)
        (at box3 place1)
        (at car1 place2)
        (at car2 place3)
        (at car3 place2)
    ))
)
